---
driver:
  name: vagrant
  vm_hostname: glance.ci.local
  use_sudo: false
  customize:
    memory: 512


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  formula: glance
  log_level: info
  state_top:
    base:
      "*":
        - glance
  pillars:
    top.sls:
      base:
        "*":
          - glance
  grains:
    noservices: False


verifier:
  name: inspec
  sudo: true


platforms:
  #- name: ubuntu-14.04
  - name: ubuntu-16.04
  #- name: centos-7.1


suites:

  - name: cluster
    provisioner:
      pillars-from-files:
        glance.sls: tests/pillar/cluster.sls

  - name: single_ceph
    provisioner:
      pillars-from-files:
        glance.sls: tests/pillar/single_ceph.sls

  - name: single
    provisioner:
      pillars-from-files:
        glance.sls: tests/pillar/single.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
